name: check

on:
  push:
    branches:
      - main

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Checkout private repo (script only)
        uses: actions/checkout@v4
        with:
          repository: jxrno/discord-c
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: discord-c

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd discord-c
          npm install axios

      - name: Run script
        run: |
          node discord-c/script.js || echo "Script exited"

      - name: Commit and push results
        if: success() || failure()
        run: |
          date +%Y-%m-%d_%H-%M-%S > date
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add date checked.json valid.json 2>/dev/null || true
          git commit -m "update usernames" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/JXRNO/Waffeling.git HEAD:main

